port: 8080
socks-port: 1080
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
proxy-groups:
  - name: "\U0001F680 节点选择"
    type: select
    proxies:
      - "\U0001F1ED\U0001F1F0 香港节点"
      - "\U0001F1E8\U0001F1F3 台湾节点"
      - "\U0001F1F8\U0001F1EC 狮城节点"
      - "\U0001F1EF\U0001F1F5 日本节点"
      - "\U0001F1FA\U0001F1F2 美国节点"
      - "\U0001F1F0\U0001F1F7 韩国节点"
      - "\U0001F680 手动切换"
      - ☯️ 故障转移
      - DIRECT
  - name: ☯️ 故障转移
    type: fallback
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
    url: http://www.gstatic.com/generate_204
    interval: '180'
    filter: "(新加坡|Singapore|SG|台湾|Taiwan|TW|香港|HK|Hong Kong|韩国|日本|Japan)"
  - name: "\U0001F3AE 游戏人间"
    type: select
    proxies:
      - ☯️ 故障转移
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
  - name: "\U0001F4BC 勤勤恳恳"
    type: select
    proxies:
      - ☯️ 故障转移
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
  - name: "\U0001F916 人工智障"
    type: select
    proxies:
      - ☯️ 故障转移
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
  - name: "\U0001F3B6 TikTok"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
  - name: "\U0001F680 手动切换"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
  - name: "\U0001F4F2 电报消息"
    type: select
    proxies:
      - "\U0001F680 节点选择"
      - "\U0001F1F8\U0001F1EC 狮城节点"
      - "\U0001F1ED\U0001F1F0 香港节点"
      - "\U0001F1E8\U0001F1F3 台湾节点"
      - "\U0001F1EF\U0001F1F5 日本节点"
      - "\U0001F1FA\U0001F1F2 美国节点"
      - "\U0001F1F0\U0001F1F7 韩国节点"
      - "\U0001F680 手动切换"
      - DIRECT
  - name: "\U0001F3A5 奈飞视频"
    type: select
    proxies:
      - "\U0001F680 手动切换"
    use:
      - WgetCloud
  - name: "\U0001F3A5 Disney"
    type: select
    proxies:
      - "\U0001F680 手动切换"
    use:
      - WgetCloud
  - name: "\U0001F4FA 哔哩哔哩"
    type: select
    proxies:
      - "\U0001F3AF 全球直连"
    use:
      - WgetCloud
    filter: "(台|新北|彰化|TW|Taiwan|港|HK|Hong Kong)"
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - DIRECT
      - "\U0001F680 节点选择"
      - "\U0001F1FA\U0001F1F2 美国节点"
      - "\U0001F1ED\U0001F1F0 香港节点"
      - "\U0001F1E8\U0001F1F3 台湾节点"
      - "\U0001F1F8\U0001F1EC 狮城节点"
      - "\U0001F1EF\U0001F1F5 日本节点"
      - "\U0001F1F0\U0001F1F7 韩国节点"
      - "\U0001F680 手动切换"
  - name: "\U0001F34E 苹果服务"
    type: select
    proxies:
      - DIRECT
      - "\U0001F680 节点选择"
      - "\U0001F1FA\U0001F1F2 美国节点"
      - "\U0001F1ED\U0001F1F0 香港节点"
      - "\U0001F1E8\U0001F1F3 台湾节点"
      - "\U0001F1F8\U0001F1EC 狮城节点"
      - "\U0001F1EF\U0001F1F5 日本节点"
      - "\U0001F1F0\U0001F1F7 韩国节点"
      - "\U0001F680 手动切换"
  - name: "\U0001F3AE 游戏平台"
    type: select
    proxies:
      - DIRECT
      - "\U0001F680 节点选择"
      - "\U0001F1FA\U0001F1F2 美国节点"
      - "\U0001F1ED\U0001F1F0 香港节点"
      - "\U0001F1E8\U0001F1F3 台湾节点"
      - "\U0001F1F8\U0001F1EC 狮城节点"
      - "\U0001F1EF\U0001F1F5 日本节点"
      - "\U0001F1F0\U0001F1F7 韩国节点"
      - "\U0001F680 手动切换"
  - name: "\U0001F3AF 全球直连"
    type: select
    proxies:
      - DIRECT
      - "\U0001F680 节点选择"
  - name: "\U0001F41F 漏网之鱼"
    type: select
    proxies:
      - "\U0001F680 节点选择"
      - DIRECT
      - "\U0001F1ED\U0001F1F0 香港节点"
      - "\U0001F1E8\U0001F1F3 台湾节点"
      - "\U0001F1F8\U0001F1EC 狮城节点"
      - "\U0001F1EF\U0001F1F5 日本节点"
      - "\U0001F1FA\U0001F1F2 美国节点"
      - "\U0001F1F0\U0001F1F7 韩国节点"
      - "\U0001F680 手动切换"
  - name: "\U0001F1ED\U0001F1F0 香港节点"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
    filter: "(港|HK|Hong Kong)"
  - name: "\U0001F1EF\U0001F1F5 日本节点"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
    filter: "(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)"
  - name: "\U0001F1FA\U0001F1F2 美国节点"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
    filter: "(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)"
  - name: "\U0001F1F8\U0001F1EC 狮城节点"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
    filter: "(新加坡|坡|狮城|SG|Singapore)"
  - name: "\U0001F1E8\U0001F1F3 台湾节点"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
    filter: "(台|新北|彰化|TW|Taiwan)"
  - name: "\U0001F1F0\U0001F1F7 韩国节点"
    type: select
    use:
      - WgetCloud
      - 橘色云
      - Miaona!
      - 极速
    filter: "(KR|Korea|KOR|首尔|韩|韓)"
script:
  shortcuts: # 使用表达式编写自定义规则
    # 4483 与 9305 为 BiliBili 的 QUIC CDN
    quic: network == 'udp' and (dst_port == 443 or dst_port == 4483 or dst_port == 9305)
rules:
  - SCRIPT,quic,REJECT,no-track
  - "geosite,bilibili,\U0001F4FA 哔哩哔哩"
  - "geosite,tiktok,\U0001F3B6 TikTok"
  - "geosite,ai,\U0001F916 人工智障"
  - "geosite,disney,\U0001F3A5 Disney"
  - geosite,microsoft-cn,Ⓜ️ 微软服务
  - "geosite,games-cn,\U0001F3AE 游戏平台"
  - "geoip,netflix,\U0001F3A5 奈飞视频"
  - "geosite,apple-cn,\U0001F34E 苹果服务"
  - "geosite,google-cn,\U0001F680 节点选择"
  - "geosite,proxy,\U0001F680 节点选择"
  - "geoip,telegram,\U0001F4F2 电报消息"
  - geosite,private,DIRECT
  - geoip,private,DIRECT
  - "geosite,cn,\U0001F3AF 全球直连"
  - "geoip,cn,\U0001F3AF 全球直连"
  - "MATCH,\U0001F41F 漏网之鱼"
proxy-providers:
  WgetCloud:
    override:
      additional-suffix: "『❤Wget』"
    type: http
    url: http://jia.hdrly.top:25500/sub?target=clash&url=https%3A%2F%2Fbava8u2znaj6bdzzjnfb.wgetcloud.online%2Flink%2FBPZTYrqNJAbgVKU&config=https%3A%2F%2Fraw.githubusercontent.com%2Fhelp-eeeee%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&exclude=%E6%B5%81%E9%87%8F%7C%E5%A5%97%E9%A4%90&emoji=true&udp=true&sort=false&scv=true&list=true
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 360
  橘色云:
    override:
      additional-suffix: "『\U0001F9E1橘色云』"
    type: http
    url: https://sub1.haiqilai.lol/api/v1/client/subscribe?token=ed55326225ddf7745eb3c79290ca548f
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 360
  Miaona!:
    override:
      additional-suffix: "『\U0001F49BMiaona!』"
    type: http
    url: https://miaona.org/api/v1/client/subscribe?token=b1d360cab0dd6185bdb53aed17471a10
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 360
  极速:
    override:
      additional-suffix: "『\U0001F49A极速』"
    type: http
    url: https://jsjc.cfd/api/v1/client/subscribe?token=498c14b3176a0af4dd3223a4876b93e3
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 360
find-process-mode: off
keep-alive-idle: 600
keep-alive-interval: 15
ipv6: false
external-ui: ui
external-ui-name: YACD
external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip
secret: 27541
profile:
  store-selected: true
  store-fake-ip: true
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
tun:
  enable: false
  stack: system
  device: tun
  mtu: 9000
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  respect-rules: false
  ipv6: false
  use-system-hosts: false
  use-hosts: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://8.8.8.8/dns-query
    - tls://8.8.8.8:853
    - https://1.1.1.1/dns-query
geodata-mode: true
geodata-loader: standard
geox-url:
  geosite: https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash/geosite-all.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb
  geoip: https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash/geoip-all.dat
  asn: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 24
